export const initialCalculationData = {
  isTwoDimension: false,
  isThreeDimension: false,
  isTexture: false,
  hoursInOffice: "",
  hoursForFilesPreparing: "",
  numberOfCommutes: "",
  numberOfForms: "",
  companyName: "",
  material: "",
  surfaceArea: undefined,
  estimatedTime: undefined,
  descriptiom: "",
  total: 0,
};
